<style>
p.newsspec_7655__not-supported {
	background: black;
	color: white;
	padding: 0.5em;
}
</style>
<p class="newsspec_7655__not-supported">We are experimenting with a new type of interactive video. This format is currently only available on a specific set of desktop and tablet devices and unavailable in Internet Explorer. As the prototype develops we will increase the range of browsers and devices supported.</p>